### ISSUE TITLE
`-w` option to get all tabs (feature request)

### ISSUE THREAD

**Issue by ericsoco** [bassarisse/google-spreadsheet-to-json#10]
Not sure exactly how this would work, but something like `-w *`, which would instruct iterating over each tab in `spreadsheet.getInfo().worksheets`.

**Comment by ericsoco** [comment]
https://github.com/theoephraim/node-google-spreadsheet#googlespreadsheetgetinfocallback

**Comment by bassarisse** [comment]
Had trouble supporting this through a `*` wildcard as suggested, so now there's a new argument to list all worksheets (https://github.com/bassarisse/google-spreadsheet-to-json/commit/70662f0b7f5a7b0adce45d25924c091236d57ddc). New version will be published soon.
