### ISSUE TITLE
Saving data to JSON file using Node API

### ISSUE THREAD

**Issue by m370** [bassarisse/google-spreadsheet-to-json#16]
Easy to save to a file in the CLI, but can't seem to do it in the Node API. Tried a few variants of the code below. Is this possible when used within a js file?

gsjson({
  spreadsheetId: 'spreadsheetId',
  file: 'data.json'
})

**Comment by m370** [comment]
Write to file required. Code is here https://pastebin.com/zGRKekhY

**Comment by bassarisse** [comment]
Yes, for the Node API, I think it's better to just output the object, then the user decides what to do with it.
