### ISSUE TITLE
Access Google 

### ISSUE THREAD

**Issue by uliaaan** [bassarisse/google-spreadsheet-to-json#18]
I have got private spreadsheets. Google give me access token for 3600 sec. What's wrong? I need token long-live token

**Comment by bassarisse** [comment]
For that you can use a Service Account credential, as mentioned in the Readme.

For a step-by-step process on how to use this auth method, check the Readme of the lib we use here: https://github.com/theoephraim/node-google-spreadsheet#service-account-recommended-method
