### ISSUE TITLE
[question] to get image raw in cell with the =IMAGE(“URL”) function?

### ISSUE THREAD

**Issue by joneldiablo** [bassarisse/google-spreadsheet-to-json#21]
Exists any way to get the data as base64 or raw data in the json response if I have a column images with the **=IMAGE('url')** function?

**Comment by bassarisse** [comment]
That would be a great feature, but apparently we have API limitations:

https://github.com/theoephraim/node-google-spreadsheet/issues/79

However, if you're using the Node API, you could store the image's URL directly as the cell value, and then fetch them for yourself.
