### ISSUE TITLE
Using the allWorksheets option in Node

### ISSUE THREAD

**Issue by sugarcup** [bassarisse/google-spreadsheet-to-json#23]
I have tried a few attempts and looked through the docs to get the AllWorksheets option in Node, but not having any luck. Please confirm the correct syntax.

gsjson({
    spreadsheetId: 'abc123456789',
    worksheets: 'allWorksheets'
})

**Comment by bassarisse** [comment]
The correct usage would be like this:

```javascript
gsjson({
    spreadsheetId: 'abc123456789',
    allWorksheets: true,
})
```
