### ISSUE TITLE
Hidden Columns

### ISSUE THREAD

**Issue by jazzybeat** [bassarisse/google-spreadsheet-to-json#4]
Hidden columns gets exported if it includes formula in the cell. The only way around this is to delete columns while exporting.

**Comment by bassarisse** [comment]
Unfortunately, the package I rely to read the spreadsheet does no offer this information about the cells. We could also offer an option to ignore columns, what do you think?

**Comment by deepfriedbrain** [comment]
An option to ignore columns would be useful. Thanks!

**Comment by bassarisse** [comment]
Just added some options to ignore rows and columns (https://github.com/bassarisse/google-spreadsheet-to-json/commit/e5b06d2a9c75f274594af3fb12860779939ec90e), I'll publish soon.
