### ISSUE TITLE
how to use a service account?

### ISSUE THREAD

**Issue by peter-mouland** [bassarisse/google-spreadsheet-to-json#9]
the readme shows you how to create a temporary token.
what are the settings needed to use a service account?
will the dependency need updating?

https://www.npmjs.com/package/google-spreadsheet#service-account-recommended-method

**Comment by bassarisse** [comment]
Implemented in https://github.com/bassarisse/google-spreadsheet-to-json/commit/cf5d69e98b66693dd96eff93d5755dd1360b0ac5. I'll publish a new version soon.
